name: Feature Plan
description: Create a feature plan as part of a milestone or project.
body:
  - type: input
    id: feature-name
    attributes:
      label: "Feature Name:"
      description: |
        The name or short summary of the feature you want implemented.
      placeholder: "Refactor Everything"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description:"
      description: |
        Explain everything in the feature, why the feature should be added, what other feature this feature is part of, etc.
      placeholder: |
        "Remove all legacy code."
        "Replace it with new, better code."
    validations:
      required: true
  - type: textarea
    id: children
    attributes:
      label: "Prerequisites:"
      description: |
        Other planned features that must be implemented before this feature can be implemented.
      placeholder: "#1"
    validations:
      required: false
  - type: textarea
    id: parents
    attributes:
      label: "Required By:"
      description: |
        Other planned features that cannot be implemented before this feature is implemented.
    validations:
      required: false
