
// Tribes
#define FEATURE_GAROU_TRIBE "garou_tribe"

/// No clan.
#define TRIBE_RONIN "Ronin"

#define TRIBE_BLACK_FURIES "Black Furies"
#define TRIBE_BONEGNAWERS "Bonegnawers"
#define TRIBE_CHILDREN_OF_GAIA "Children of Gaia"
#define TRIBE_FIANNA "Fianna"
#define TRIBE_GALESTALKERS "Galestalkers"
#define TRIBE_GET_OF_FENRIS "Get of Fenris"
#define TRIBE_GHOST_COUNCIL "Ghost Council"
#define TRIBE_GLASSWALKERS "Glasswalkers"
#define TRIBE_RED_TALONS "Red Talons"
#define TRIBE_SHADOW_LORDS "Shadow Lords"
#define TRIBE_SILENTSTRIDERS "Silent Striders"
#define TRIBE_SILVER_FANGS "Silver Fangs"
#define TRIBE_STARGAZERS "Stargazers"
#define TRIBE_BLACK_SPIRAL_DANCERS "Black Spiral Dancers"

#define TRIBE_CORAX "Corax" // DARKPACK TODO - CORAX

#define TRIBE_ALL list(TRIBE_RONIN, TRIBE_GALESTALKERS, TRIBE_CHILDREN_OF_GAIA, TRIBE_GHOST_COUNCIL, TRIBE_FIANNA, TRIBE_GET_OF_FENRIS, TRIBE_BLACK_FURIES, TRIBE_SILVER_FANGS, TRIBE_SILENTSTRIDERS, TRIBE_RED_TALONS, TRIBE_STARGAZERS, TRIBE_GLASSWALKERS, TRIBE_BONEGNAWERS, TRIBE_SHADOW_LORDS, TRIBE_BLACKSPIRALDANCERS, TRIBE_CORAX)
#define TRIBE_GAIA list(TRIBE_GALESTALKERS, TRIBE_CHILDREN_OF_GAIA, TRIBE_GHOST_COUNCIL, TRIBE_FIANNA, TRIBE_GET_OF_FENRIS, TRIBE_BLACK_FURIES, TRIBE_SILVER_FANGS, TRIBE_SILENTSTRIDERS, TRIBE_RED_TALONS, TRIBE_STARGAZERS, TRIBE_GLASSWALKERS, TRIBE_BONEGNAWERS, TRIBE_SHADOW_LORDS, TRIBE_CORAX)
#define TRIBE_WYLD list(TRIBE_GALESTALKERS, TRIBE_CHILDREN_OF_GAIA, TRIBE_GHOST_COUNCIL, TRIBE_FIANNA, TRIBE_GET_OF_FENRIS, TRIBE_BLACK_FURIES, TRIBE_SILVER_FANGS, TRIBE_SILENTSTRIDERS, TRIBE_RED_TALONS, TRIBE_STARGAZERS, TRIBE_SHADOW_LORDS, TRIBE_CORAX)
#define TRIBE_WEAVER list(TRIBE_GLASSWALKERS, TRIBE_BONEGNAWERS)
#define TRIBE_WYRM list(TRIBE_BLACK_SPIRAL_DANCERS)

GLOBAL_LIST_INIT(garou_tribes, list(
	TRIBE_BLACK_FURIES = TRIBE_BLACK_FURIES,
	TRIBE_BLACK_SPIRAL_DANCERS = TRIBE_BLACK_SPIRAL_DANCERS,
	TRIBE_BONEGNAWERS = TRIBE_BONEGNAWERS,
	TRIBE_GLASSWALKERS = TRIBE_GLASSWALKERS,
	TRIBE_CHILDREN_OF_GAIA = TRIBE_CHILDREN_OF_GAIA,
	TRIBE_FIANNA = TRIBE_FIANNA,
	TRIBE_GET_OF_FENRIS = TRIBE_GET_OF_FENRIS,
	TRIBE_RED_TALONS = TRIBE_RED_TALONS,
	TRIBE_SHADOW_LORDS = TRIBE_SHADOW_LORDS,
	TRIBE_SILVER_FANGS = TRIBE_SILVER_FANGS,
	TRIBE_STARGAZERS = TRIBE_STARGAZERS,
	TRIBE_GHOST_COUNCIL = TRIBE_GHOST_COUNCIL,
	TRIBE_GALESTALKERS = TRIBE_GALESTALKERS,
	TRIBE_SILENTSTRIDERS = TRIBE_SILENTSTRIDERS,
	TRIBE_RONIN = TRIBE_RONIN,
))
