// Breeds
GLOBAL_LIST_INIT(garou_breeds, list(
	BREED_HOMID = /mob/living/carbon/human/fera,
	BREED_LUPUS = /mob/living/carbon/human/fera/lupus,
	BREED_CRINOS = /mob/living/carbon/human/fera/crinos,
))

// Auspices
#define FEATURE_GAROU_AUSPICE "garou_auspice"

#define AUSPICE_RAGABASH "Ragabash"
#define AUSPICE_THEURGE "Theurge"
#define AUSPICE_PHILODOX "Philodox"
#define AUSPICE_AHROUN "Ahroun"
#define AUSPICE_GALLLIARD "Galliard"

GLOBAL_LIST_INIT(garou_auspices, list(
	AUSPICE_RAGABASH = AUSPICE_RAGABASH,
	AUSPICE_THEURGE = AUSPICE_THEURGE,
	AUSPICE_PHILODOX = AUSPICE_PHILODOX,
	AUSPICE_AHROUN = AUSPICE_AHROUN,
	AUSPICE_GALLLIARD = AUSPICE_GALLLIARD,
))

// Tribes
#define FEATURE_GAROU_TRIBE "garou_tribe"

#define TRIBE_BLACK_FURIES "Black Furies"
#define TRIBE_BLACK_SPIRAL_DANCERS "Black Spiral Dancers"
#define TRIBE_BONEGNAWERS "Bonegnawers"
#define TRIBE_GLASSWALKERS "Glasswalkers"
#define TRIBE_CHILDREN_OF_GAIA "Children of Gaia"
#define TRIBE_FIANNA "Fianna"
#define TRIBE_GET_OF_FENRIS "Get of Fenris"
#define TRIBE_RED_TALONS "Red Talons"
#define TRIBE_SHADOW_LORDS "Shadow Lords"
#define TRIBE_SILVER_FANGS "Silver Fangs"
#define TRIBE_STARGAZERS "Stargazers"
#define TRIBE_SKINDANCERS "Skindancers"
#define TRIBE_GHOST_COUNCIL "Ghost Council"
#define TRIBE_GALESTALKERS "Galestalkers"
#define TRIBE_RONIN "Ronin"

GLOBAL_LIST_INIT(garou_tribes, list(
	TRIBE_BLACK_FURIES = TRIBE_BLACK_FURIES,
	TRIBE_BLACK_SPIRAL_DANCERS = TRIBE_BLACK_SPIRAL_DANCERS,
	TRIBE_BONEGNAWERS = TRIBE_BONEGNAWERS,
	TRIBE_GLASSWALKERS = TRIBE_GLASSWALKERS,
	TRIBE_CHILDREN_OF_GAIA = TRIBE_CHILDREN_OF_GAIA,
	TRIBE_FIANNA = TRIBE_FIANNA,
	TRIBE_GET_OF_FENRIS = TRIBE_GET_OF_FENRIS,
	TRIBE_RED_TALONS = TRIBE_RED_TALONS,
	TRIBE_SHADOW_LORDS = TRIBE_SHADOW_LORDS,
	TRIBE_SILVER_FANGS = TRIBE_SILVER_FANGS,
	TRIBE_STARGAZERS = TRIBE_STARGAZERS,
	TRIBE_SKINDANCERS = TRIBE_SKINDANCERS,
	TRIBE_GHOST_COUNCIL = TRIBE_GHOST_COUNCIL,
	TRIBE_GALESTALKERS = TRIBE_GALESTALKERS,
	TRIBE_RONIN = TRIBE_RONIN,
))
