// Auspices
#define FEATURE_GAROU_AUSPICE "garou_auspice"

#define AUSPICE_RAGABASH "Ragabash"
#define AUSPICE_THEURGE "Theurge"
#define AUSPICE_PHILODOX "Philodox"
#define AUSPICE_AHROUN "Ahroun"
#define AUSPICE_GALLIARD "Galliard"

#define AUSPICE_NONE "Stolen Moon"

GLOBAL_LIST_INIT(garou_auspices, list(
	AUSPICE_RAGABASH = AUSPICE_RAGABASH,
	AUSPICE_THEURGE = AUSPICE_THEURGE,
	AUSPICE_PHILODOX = AUSPICE_PHILODOX,
	AUSPICE_AHROUN = AUSPICE_AHROUN,
	AUSPICE_GALLIARD = AUSPICE_GALLIARD,
	AUSPICE_NONE = AUSPICE_NONE,
))
