
// associative list used by dementation and the derangement quirk
GLOBAL_LIST_INIT(derangement_phrases,list(
	"Evil crouches" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Crouch.ogg',
	"Death" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Death.ogg',
	"DIE!" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Die.ogg',
	"I smell a rancid grave" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Grave.ogg',
	"Rustling robes of the Reaper" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Reaper.ogg',
	"All are blind whose eyes are closed" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Blind.ogg',
	"The drove is a terrible mistress" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Mistress.ogg',
	"Wishes and words sprout from the same seed" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Wishes_Words.ogg',
	"A dark light from your death" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Dark_Light.ogg',
	"Hemlock for the deceivers" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Hemlock.ogg',
	"It has two mouths to lick from" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Two_Mouths.ogg',
	"Deep of the Atlantic, dark, dreaming, sleeping" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Atlantic.ogg',
	"Can't see, can't see! Where have my eyes gone to?" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Eyes.ogg',
	"Heloise said you. Cranberry sauce. Hotel foxtrot" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Heloise.ogg',
	"Stop doing that. Mother shan't be too pleased. None too pleased" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Mother.ogg',
	"Those lips bleed a putrid poison" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Putrid.ogg',
	"Rat tails, cat tails, coat tails, all tales" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Tails.ogg',
	"It's not fair! I wanted to" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Not_Fair.ogg',
	"Pennies for your eyes in its pockets" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Pennies.ogg',
	"Why is it troubled?" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Troubled.ogg',
	"Ask about the free arsenic" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Arsenic.ogg',
	"Blood brings the vicious beast" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Beast.ogg',
	"I see daggers hang on his breath" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Daggers.ogg',
	"Bone round in melody and word layed in rain" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Bone.ogg',
	"Cemetery runoff congealing at the door" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Cemetery.ogg',
	"Maggots love you. Trust me" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Maggots.ogg',
	"Mast lay shrouded and the moon is melting" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Moon.ogg',
	"Try the corpse in the oven with peppers and fur" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Peppers.ogg',
	"Souls draped in rotten tatters and Father dances in the dark" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Souls.ogg',
	"Make the tallow from the fat of a hangman" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Tallow.ogg',
	"Bent like a calf for the butcher" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Calf.ogg',
	"You're in for it now" = 'modular_darkpack/modules/powers/sounds/dementation/speech/In_For_It.ogg',
	"They're coming" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Theyre_Coming.ogg',
	"It casts a crooked shadow" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Shadow.ogg',
	"Elkabo, elkabo, pixy queen where all is green" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Elkabo.ogg',
	"It's a tangle of asps" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Asps.ogg',
	"Sealed with the kiss of swine" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Swine.ogg',
	"A trick with two tongues" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Tongues.ogg',
	"The very thought falls to the flame" = 'modular_darkpack/modules/powers/sounds/dementation/speech/Flame.ogg'
))
